{{$protocol := DefaultParam .CL2_PROTOCOL "TCP"}}
{{$numberOfServers := DefaultParam .CL2_NUMBER_OF_SERVERS 5}}
{{$numberOfClients := DefaultParam .CL2_NUMBER_OF_CLIENTS 5}}

name: network_performance 
namespace:
  number: 1
steps:
- name: Start network performance measurement
  measurements:
    - Identifier: NetworkPerformanceMetrics
      Method: NetworkPerformanceMetrics
      Params:
        action: start
        duration: 10s
        protocol: {{$protocol}}
        numberOfServers: {{$numberOfServers}}
        numberOfClients: {{$numberOfClients}}
- name: Gather network performance measurement
  measurements:
    - Identifier: NetworkPerformanceMetrics
      Method: NetworkPerformanceMetrics
      Params:
        action: gather 
