name: test
automanagednamespaces: 0
namespace:
  number: 1
  prefix: test-1ca4jd
  deletestalenamespaces: false
  deleteautomanagednamespaces: true
  enableexistingnamespaces: false
  deletenamespacetimeout: 600000000000
steps:
- phases: []
  measurements:
  - method: PodStartupLatency
    params:
      action: start
      labelSelector: group = test-pod
      threshold: 1000s
    identifier: PodStartupLatency
    instances: []
  - method: WaitForControlledPodsRunning
    params:
      action: start
      apiVersion: apps/v1
      kind: Deployment
      labelSelector: group = test-deployment
      operationTimeout: 1000s
    identifier: WaitForControlledPodsRunning
    instances: []
  module:
    path: ""
    params: {}
  name: Start measurements
- phases:
  - namespacerange:
      min: 1
      max: 1
      basename: null
    namespacelist: []
    replicaspernamespace: 1
    tuningset: Uniform5qps
    objectbundle:
    - basename: test-deployment
      objecttemplatepath: deployment.yaml
      templatefillmap:
        CpuRequest: 30m
        MemoryRequest: 64Mi
        Replicas: 100
      listunknownobjectoptions: null
  measurements: []
  module:
    path: ""
    params: {}
  name: Create deployment
- phases: []
  measurements:
  - method: WaitForControlledPodsRunning
    params:
      action: gather
    identifier: WaitForControlledPodsRunning
    instances: []
  module:
    path: ""
    params: {}
  name: Wait for pods to be running
- phases: []
  measurements:
  - method: PodStartupLatency
    params:
      action: gather
    identifier: PodStartupLatency
    instances: []
  module:
    path: ""
    params: {}
  name: Measure pod startup latency
tuningsets:
- name: Uniform5qps
  initialdelay: 0
  qpsload:
    qps: 5
  randomizedload: null
  steppedload: null
  timelimitedload: null
  randomizedtimelimitedload: null
  parallelismlimitedload: null
  globalqpsload: null
chaosmonkey:
  nodefailure: null
  excludednodes: {}
