name: node-throughput
automanagednamespaces: 0
namespace:
  number: 1
  prefix: test-wjsv3d
  deletestalenamespaces: false
  deleteautomanagednamespaces: true
  enableexistingnamespaces: false
  deletenamespacetimeout: 600000000000
steps:
- phases: []
  measurements:
  - method: WindowsResourceUsagePrometheus
    params:
      action: start
    identifier: WindowsResourceUsagePrometheus
    instances: []
  - method: APIResponsivenessPrometheus
    params:
      action: start
    identifier: APIResponsivenessPrometheusSimple
    instances: []
  - method: PodStartupLatency
    params:
      action: start
      labelSelector: group = latency
      threshold: 60m
    identifier: PodStartupLatency
    instances: []
  module:
    path: ""
    params: {}
  name: ""
- phases: []
  measurements:
  - method: WaitForControlledPodsRunning
    params:
      action: start
      apiVersion: v1
      kind: ReplicationController
      labelSelector: group = latency
      operationTimeout: 90m
    identifier: WaitForRunningLatencyRCs
    instances: []
  module:
    path: ""
    params: {}
  name: ""
- phases:
  - namespacerange:
      min: 1
      max: 1
      basename: null
    namespacelist: []
    replicaspernamespace: 1000
    tuningset: UniformQPS
    objectbundle:
    - basename: latency-pod-rc
      objecttemplatepath: rc.yaml
      templatefillmap:
        Group: latency
        Image: mcr.microsoft.com/windows/servercore:ltsc2022
        Replicas: 1
      listunknownobjectoptions: null
  measurements: []
  module:
    path: ""
    params: {}
  name: ""
- phases: []
  measurements:
  - method: WaitForControlledPodsRunning
    params:
      action: gather
    identifier: WaitForRunningLatencyRCs
    instances: []
  - method: WindowsResourceUsagePrometheus
    params:
      action: gather
    identifier: WindowsResourceUsagePrometheus
    instances: []
  module:
    path: ""
    params: {}
  name: ""
- phases:
  - namespacerange:
      min: 1
      max: 1
      basename: null
    namespacelist: []
    replicaspernamespace: 0
    tuningset: UniformQPS
    objectbundle:
    - basename: latency-pod-rc
      objecttemplatepath: rc.yaml
      templatefillmap: {}
      listunknownobjectoptions: null
  measurements: []
  module:
    path: ""
    params: {}
  name: ""
- phases: []
  measurements:
  - method: WaitForControlledPodsRunning
    params:
      action: gather
    identifier: WaitForRunningLatencyRCs
    instances: []
  module:
    path: ""
    params: {}
  name: ""
- phases: []
  measurements:
  - method: PodStartupLatency
    params:
      action: gather
    identifier: PodStartupLatency
    instances: []
  module:
    path: ""
    params: {}
  name: ""
- phases: []
  measurements:
  - method: APIResponsivenessPrometheus
    params:
      action: gather
      enableViolations: true
      summaryName: APIResponsivenessPrometheus_simple
      useSimpleLatencyQuery: true
    identifier: APIResponsivenessPrometheusSimple
    instances: []
  module:
    path: ""
    params: {}
  name: ""
tuningsets:
- name: UniformQPS
  initialdelay: 0
  qpsload:
    qps: 0.03
  randomizedload: null
  steppedload: null
  timelimitedload: null
  randomizedtimelimitedload: null
  parallelismlimitedload: null
  globalqpsload: null
chaosmonkey:
  nodefailure: null
  excludednodes: {}
