name: density
automanagednamespaces: 0
namespace:
  number: 1
  prefix: test-89474e
  deletestalenamespaces: false
  deleteautomanagednamespaces: true
  enableexistingnamespaces: false
  deletenamespacetimeout: 600000000000
steps:
- phases: []
  measurements:
  - method: PodStartupLatency
    params:
      action: start
      labelSelector: group = saturation
      threshold: 330s
    identifier: SaturationPodStartupLatency
    instances: []
  - method: WaitForControlledPodsRunning
    params:
      action: start
      apiVersion: apps/v1
      kind: Deployment
      labelSelector: group = saturation
      operationTimeout: 1200s
    identifier: WaitForRunningSaturationDeployments
    instances: []
  - method: SchedulingThroughput
    params:
      action: start
      labelSelector: group = saturation
    identifier: SchedulingThroughput
    instances: []
  module:
    path: ""
    params: {}
  name: Starting saturation pod measurements
- phases:
  - namespacerange:
      min: 1
      max: 1
      basename: null
    namespacelist: []
    replicaspernamespace: 1
    tuningset: Uniform5qps
    objectbundle:
    - basename: saturation-deployment
      objecttemplatepath: deployment.yaml
      templatefillmap:
        CpuRequest: 30m
        Group: saturation
        MemoryRequest: 50Mi
        Replicas: 3000
      listunknownobjectoptions: null
  measurements: []
  module:
    path: ""
    params: {}
  name: Creating saturation pods
- phases: []
  measurements:
  - method: WaitForControlledPodsRunning
    params:
      action: gather
    identifier: WaitForRunningSaturationDeployments
    instances: []
  module:
    path: ""
    params: {}
  name: Waiting for saturation pods to be running
- phases: []
  measurements:
  - method: PodStartupLatency
    params:
      action: gather
    identifier: SaturationPodStartupLatency
    instances: []
  - method: SchedulingThroughput
    params:
      action: gather
      enableViolations: true
      threshold: 0
    identifier: SchedulingThroughput
    instances: []
  module:
    path: ""
    params: {}
  name: Collecting saturation pod measurements
- phases:
  - namespacerange:
      min: 1
      max: 1
      basename: null
    namespacelist: []
    replicaspernamespace: 0
    tuningset: Uniform5qps
    objectbundle:
    - basename: saturation-deployment
      objecttemplatepath: deployment.yaml
      templatefillmap: {}
      listunknownobjectoptions: null
  measurements: []
  module:
    path: ""
    params: {}
  name: Deleting saturation pods
- phases: []
  measurements:
  - method: WaitForControlledPodsRunning
    params:
      action: gather
    identifier: WaitForRunningSaturationDeployments
    instances: []
  module:
    path: ""
    params: {}
  name: Waiting for saturation pods to be deleted
tuningsets:
- name: Uniform5qps
  initialdelay: 0
  qpsload:
    qps: 5
  randomizedload: null
  steppedload: null
  timelimitedload: null
  randomizedtimelimitedload: null
  parallelismlimitedload: null
  globalqpsload: null
chaosmonkey:
  nodefailure: null
  excludednodes: {}
