# ASSUMPTIONS:
# - This test is designed for 1-node cluster.

#Constants
{{$POD_COUNT := DefaultParam .CL2_POD_COUNT 1000}}
{{$POD_THROUGHPUT := DefaultParam .CL2_POD_THROUGHPUT 0.03}}
{{$CONTAINER_IMAGE := DefaultParam .CL2_CONTAINER_IMAGE "mcr.microsoft.com/windows/servercore:ltsc2022 "}}
{{$POD_STARTUP_LATENCY_THRESHOLD := DefaultParam .CL2_POD_STARTUP_LATENCY_THRESHOLD "60m"}}
{{$OPERATION_TIMEOUT := DefaultParam .CL2_OPERATION_TIMEOUT "90m"}}

name: node-throughput

namespace:
  number: 1

tuningSets:
- name: UniformQPS
  qpsLoad:
    qps: 1 # {{$POD_THROUGHPUT}}

steps:
- name: Start measurements
  measurements:
  - Identifier: PodStartupLatency
    Method: PodStartupLatency
    Params:
      action: start
      labelSelector: group = latency
      threshold: {{$POD_STARTUP_LATENCY_THRESHOLD}}
  - Identifier: WaitForControlledPodsRunning
    Method: WaitForControlledPodsRunning
    Params:
      action: start
      apiVersion: apps/v1
      kind: Deployment
      labelSelector: group = test-deployment
      operationTimeout: 120s
  # - Identifier: WindowsResourceUsagePrometheus
  #   Method: WindowsResourceUsagePrometheus
  #   Params:
  #     action: start
  # - Identifier: APIResponsivenessPrometheusSimple
  #   Method: APIResponsivenessPrometheus
  #   Params:
  #     action: start

- measurements:
  - Identifier: WaitForRunningLatencyRCs
    Method: WaitForControlledPodsRunning
    Params:
      action: start
      apiVersion: v1
      kind: ReplicationController
      labelSelector: group = latency
      operationTimeout: {{$OPERATION_TIMEOUT}}
- phases:
  - namespaceRange:
      min: 1
      max: 1
    replicasPerNamespace: {{$POD_COUNT}}
    tuningSet: UniformQPS
    objectBundle:
    - basename: latency-pod-rc
      objectTemplatePath: rc.yaml
      templateFillMap:
        Replicas: 1
        Group: latency
        Image: {{$CONTAINER_IMAGE}}
- measurements:
  - Identifier: WaitForRunningLatencyRCs
    Method: WaitForControlledPodsRunning
    Params:
      action: gather
  - Identifier: WindowsResourceUsagePrometheus
    Method: WindowsResourceUsagePrometheus
    Params:
      action: gather
- phases:
  - namespaceRange:
      min: 1
      max: 1
    replicasPerNamespace: 0
    tuningSet: UniformQPS
    objectBundle:
    - basename: latency-pod-rc
      objectTemplatePath: rc.yaml
- measurements:
  - Identifier: WaitForRunningLatencyRCs
    Method: WaitForControlledPodsRunning
    Params:
      action: gather
# Collect measurements
- measurements:
  - Identifier: PodStartupLatency
    Method: PodStartupLatency
    Params:
      action: gather
- measurements:
  - Identifier: APIResponsivenessPrometheusSimple
    Method: APIResponsivenessPrometheus
    Params:
      action: gather
      enableViolations: true
      useSimpleLatencyQuery: true
      summaryName: APIResponsivenessPrometheus_simple
