apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Name}}
  labels:
    group: test-deployment
spec:
  replicas: {{.Replicas}}
  selector:
    matchLabels:
      group: test-pod
  template:
    metadata:
      labels:
        group: test-pod
    spec:
      containers:
      - image: mcr.microsoft.com/windows/servercore:ltsc2022 
        name: {{.Name}}
  nodeSelector:
    agentpool: w22d8
    kubernetes.io/os: windows
  restartPolicy: Never