apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment

spec:
  replicas: {{.Replicas}}
  selector:
    matchLabels:
      name: test-pod
  template:
    metadata:
      labels:
        name: test-pod
    spec:
      nodeSelector:
        agentpool: w22d32
      containers:
      - image: mcr.microsoft.com/windows/servercore:ltsc2022 
        command: ["cmd"]
        args: ["/c", "ping", "127.0.0.1", "-t"]
        imagePullPolicy: IfNotPresent
        name: test-container
        ports:
        resources:
          requests:
            cpu: {{.CpuRequest}}
            memory: {{.MemoryRequest}}
      # Add not-ready/unreachable tolerations for 15 minutes so that node
      # failure doesn't trigger pod deletion.
      tolerations:
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 900
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 900
